/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java1;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import static java1.Java1.readRooms;
import static java1.Java1.readUsers;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
/**
 *
 * @author tadas
 */
public class LibraryGUIuser extends javax.swing.JFrame {

    /**
     * Creates new form LibraryGUIuser
     */
    
    
    
    Date systemTime = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd");
    User thisuser;
    DefaultListModel DLM = new DefaultListModel();
    int ListIndex;
    int skipD = 1;
    int skipW = 1;
    int skipM = 1;
    
    public LibraryGUIuser() {
        initComponents();
    }
    

    private void TakenBooks(User user)
    {  
        TakenList.setModel(DLM);
        int bookCode = 0;
        for (TakenBook book : user.getBooks()) {
            DLM.addElement(book.getIsbn() + " " + sdf.format(book.getTakenAt()));
            bookCode++;
        }
        
    }
    
    private void returnBook(User user)
    {
        user.returnBook(ListIndex);
        DLM.remove(ListIndex);
    }
    
    public LibraryGUIuser(User user)
    {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(DayRadio);
        group.add(WeekRadio);
        group.add(MonthRadio);
        TimeSkipper skipper = new TimeSkipper(systemTime);
        this.thisuser = user;
        String username = user.getUsername();
        String debt = String.valueOf(user.getPrice());
        //Show user debt
        jLabelDebt.setText(debt);
        //Show userName
        jUserName.setText(username);      
        //Show Date
        jLabelDate.setText(sdf.format(skipper.getTime()).toString());
        
        TakenBooks(user);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jUserName = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        TakeBookButton = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        ReturnBookButton = new javax.swing.JButton();
        ReserveRoomButton = new javax.swing.JButton();
        MyRoomsButton = new javax.swing.JButton();
        SkipTimeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelDebt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TakenList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        DayRadio = new javax.swing.JRadioButton();
        WeekRadio = new javax.swing.JRadioButton();
        MonthRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUserName.setText("Name");

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        TakeBookButton.setText("Take Book");
        TakeBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeBookButtonActionPerformed(evt);
            }
        });

        jLabelDate.setText("Date");

        ReturnBookButton.setText("Return Book");
        ReturnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookButtonActionPerformed(evt);
            }
        });

        ReserveRoomButton.setText("Reserve Room");
        ReserveRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveRoomButtonActionPerformed(evt);
            }
        });

        MyRoomsButton.setText("My reserved rooms");
        MyRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyRoomsButtonActionPerformed(evt);
            }
        });

        SkipTimeButton.setText("Skip Time");
        SkipTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipTimeButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Debt:");

        jLabelDebt.setText("0.0");

        TakenList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TakenList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                TakenListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(TakenList);

        jLabel1.setText("My Info:");

        DayRadio.setText("Day");

        WeekRadio.setText("Week");

        MonthRadio.setText("Month");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDate)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDebt))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TakeBookButton)
                                    .addComponent(SkipTimeButton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DayRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(WeekRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MonthRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ExitButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ReturnBookButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(ReserveRoomButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(MyRoomsButton)))))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserName)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDebt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TakeBookButton)
                    .addComponent(ReturnBookButton)
                    .addComponent(ReserveRoomButton)
                    .addComponent(MyRoomsButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(SkipTimeButton)
                    .addComponent(DayRadio)
                    .addComponent(WeekRadio)
                    .addComponent(MonthRadio))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void TakeBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeBookButtonActionPerformed
        // TODO add your handling code here:
        new GUIAddBook(thisuser).setVisible(true);
            dispose();
    }//GEN-LAST:event_TakeBookButtonActionPerformed

    private void ReturnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookButtonActionPerformed
        // TODO add your handling code here:
        returnBook(thisuser);     
    }//GEN-LAST:event_ReturnBookButtonActionPerformed

    private void TakenListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_TakenListValueChanged
        // TODO add your handling code here:
        ListIndex = TakenList.getSelectedIndex();
    }//GEN-LAST:event_TakenListValueChanged

    private void ReserveRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveRoomButtonActionPerformed
        // TODO add your handling code here:
        new GUIRooms(thisuser).setVisible(true);
            dispose();
    }//GEN-LAST:event_ReserveRoomButtonActionPerformed

    private void MyRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyRoomsButtonActionPerformed
        // TODO add your handling code here:
        new GUIMyRooms(thisuser).setVisible(true);
            dispose();
    }//GEN-LAST:event_MyRoomsButtonActionPerformed

    private void SkipTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipTimeButtonActionPerformed
        // TODO add your handling code here:
        TimeSkipper skipper = new TimeSkipper(systemTime);
        String debt = String.valueOf(thisuser.getPrice());
        if(DayRadio.isSelected())
        {
            skipper.skipDays(skipD);
            thisuser.updateDebt(skipper.getDayDifference());
            jLabelDebt.setText(debt);
            jLabelDate.setText(sdf.format(skipper.getTime()).toString());
            skipD++;
        }
        if(WeekRadio.isSelected())
        {
            skipper.skipWeeks(skipW);
            thisuser.updateDebt(skipper.getDayDifference());
            jLabelDebt.setText(debt);
            jLabelDate.setText(sdf.format(skipper.getTime()).toString());
            skipW++;
        }
        if(MonthRadio.isSelected())
        {
            skipper.skipMonths(skipM);
            thisuser.updateDebt(skipper.getDayDifference());
            jLabelDebt.setText(debt);
            jLabelDate.setText(sdf.format(skipper.getTime()).toString());
            skipM++;
        }
    }//GEN-LAST:event_SkipTimeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryGUIuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryGUIuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryGUIuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryGUIuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryGUIuser().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DayRadio;
    private javax.swing.JButton ExitButton;
    private javax.swing.JRadioButton MonthRadio;
    private javax.swing.JButton MyRoomsButton;
    private javax.swing.JButton ReserveRoomButton;
    private javax.swing.JButton ReturnBookButton;
    private javax.swing.JButton SkipTimeButton;
    private javax.swing.JButton TakeBookButton;
    private javax.swing.JList<String> TakenList;
    private javax.swing.JRadioButton WeekRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDebt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jUserName;
    // End of variables declaration//GEN-END:variables
}
